"""initial schema

Revision ID: cbae5d424f49
Revises: 
Create Date: 2026-08-24 22:03:16.566936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbae5d424f49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


EXTENSIONS = ("vector", "pg_trgm", "unaccent", "pgcrypto")

APP_ROLE = "orbi_app"

# Tabelas com tenant_id: recebem RLS forcado e politica por app.tenant_id.
TENANT_SCOPED_TABLES = (
    "tenant_settings",
    "tenant_tools",
    "users",
    "user_identities",
    "erp_connections",
    "knowledge_models",
    "catalog",
    "catalog_abbreviations",
    "entity_aliases",
    "catalog_sync_runs",
    "pending_resolutions",
    "conversation_contexts",
    "audit_logs",
    "corrections",
    "daily_usage",
)


def upgrade() -> None:
    """Upgrade schema."""
    for extension in EXTENSIONS:
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {extension}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_entity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_decision', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('policy_version_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latencies_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('erp_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('key_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', sa.String(length=8), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='pk_audit_logs'),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index('ix_audit_logs_tenant_time', 'audit_logs', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_trace', 'audit_logs', ['trace_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_capabilities'))
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite', sa.String(length=32), nullable=False),
    sa.Column('layer', sa.String(length=8), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_runs'))
    )
    op.create_table('rate_limit_counters',
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'window_started_at', 'window_seconds', name=op.f('pk_rate_limit_counters'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_roles'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('monthly_query_cap', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('channel_address', sa.String(length=32), nullable=True),
    sa.Column('channel_phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('channel_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','suspended','inactive')", name=op.f('ck_tenants_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('channel_address', name=op.f('uq_tenants_channel_address')),
    sa.UniqueConstraint('channel_phone_number_id', name=op.f('uq_tenants_channel_phone_number_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('tools',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('erp_operation', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_tools'))
    )
    op.create_table('catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('erp_entity_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('search_text', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(canonical_name, ''))", persisted=True), nullable=True),
    sa.Column('name_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('erp_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type in ('product','customer','location')", name=op.f('ck_catalog_entity_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_catalog_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog')),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'erp_entity_id', name='uq_catalog_tenant_entity')
    )
    op.create_index('ix_catalog_tenant_code', 'catalog', ['tenant_id', 'code'], unique=False)
    op.create_index('ix_catalog_tenant_type_active', 'catalog', ['tenant_id', 'entity_type', 'active'], unique=False)
    op.create_table('catalog_abbreviations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('short', sa.String(length=32), nullable=False),
    sa.Column('expanded', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_catalog_abbreviations_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_abbreviations')),
    sa.UniqueConstraint('tenant_id', 'short', name='uq_catalog_abbreviations_tenant_short')
    )
    op.create_index('ix_catalog_abbreviations_tenant', 'catalog_abbreviations', ['tenant_id'], unique=False)
    op.create_table('catalog_sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cursor', sa.String(length=64), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_upserted', sa.Integer(), nullable=False),
    sa.Column('items_deactivated', sa.Integer(), nullable=False),
    sa.Column('embeddings_computed', sa.Integer(), nullable=False),
    sa.Column('change_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('running','completed','failed','aborted')", name=op.f('ck_catalog_sync_runs_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_catalog_sync_runs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_sync_runs'))
    )
    op.create_index('ix_catalog_sync_runs_tenant', 'catalog_sync_runs', ['tenant_id', 'started_at'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('term', sa.String(length=160), nullable=True),
    sa.Column('entity_type', sa.String(length=16), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('wrong_entity_id', sa.String(length=64), nullable=True),
    sa.Column('chosen_entity_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.CheckConstraint("kind in ('tool','resolution','erp_data','expectation','unclassified')", name=op.f('ck_corrections_kind_valid')),
    sa.CheckConstraint("status in ('open','resolved','discarded')", name=op.f('ck_corrections_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_corrections_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    op.create_index('ix_corrections_tenant_status', 'corrections', ['tenant_id', 'status'], unique=False)
    op.create_table('daily_usage',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('ambiguous', sa.Integer(), nullable=False),
    sa.Column('not_found', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_daily_usage_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'day', name=op.f('pk_daily_usage'))
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('erp_entity_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('corrections', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence in ('low','confirmed')", name=op.f('ck_entity_aliases_confidence_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_entity_aliases_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'alias', name='uq_entity_aliases_tenant_type_alias')
    )
    op.create_index('ix_entity_aliases_tenant', 'entity_aliases', ['tenant_id'], unique=False)
    op.create_table('erp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('capabilities_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_knowledge_model_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_erp_connections_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_connections')),
    sa.UniqueConstraint('tenant_id', 'label', name='uq_erp_connections_tenant_id_label')
    )
    op.create_index('ix_erp_connections_tenant', 'erp_connections', ['tenant_id'], unique=False)
    op.create_table('knowledge_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('surface_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deep_model', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('abbreviations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('candidate','active','archived')", name=op.f('ck_knowledge_models_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_models_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_models')),
    sa.UniqueConstraint('tenant_id', 'adapter', 'version', name='uq_knowledge_models_version')
    )
    op.create_index('ix_knowledge_models_tenant', 'knowledge_models', ['tenant_id'], unique=False)
    op.create_table('role_capabilities',
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('capability_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['capability_code'], ['capabilities.code'], name=op.f('fk_role_capabilities_capability_code_capabilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_role_capabilities_role_code_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_code', 'capability_code', name=op.f('pk_role_capabilities'))
    )
    op.create_table('role_tools',
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_role_tools_role_code_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_name'], ['tools.name'], name=op.f('fk_role_tools_tool_name_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_code', 'tool_name', name=op.f('pk_role_tools'))
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resolution_top1_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('resolution_gap_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calibration_catalog_size', sa.Integer(), nullable=False),
    sa.Column('calibration_silent_error_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('ambiguity_options', sa.Integer(), nullable=False),
    sa.Column('pending_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('context_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenant_settings'))
    )
    op.create_table('tenant_tools',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_tools_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_name'], ['tools.name'], name=op.f('fk_tenant_tools_tool_name_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'tool_name', name=op.f('pk_tenant_tools'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('default_location_id', sa.String(length=64), nullable=True),
    sa.Column('erp_user_ref', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_users_role_code_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('conversation_contexts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('last_product_id', sa.String(length=64), nullable=True),
    sa.Column('last_product_name', sa.Text(), nullable=True),
    sa.Column('last_customer_id', sa.String(length=64), nullable=True),
    sa.Column('last_customer_name', sa.Text(), nullable=True),
    sa.Column('last_location_id', sa.String(length=64), nullable=True),
    sa.Column('last_tool', sa.String(length=64), nullable=True),
    sa.Column('recent_turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversation_contexts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_contexts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', 'channel', name=op.f('pk_conversation_contexts'))
    )
    op.create_table('pending_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('term', sa.String(length=160), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chosen_erp_entity_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_pending_resolutions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_resolutions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_resolutions'))
    )
    op.create_index('ix_pending_resolutions_lookup', 'pending_resolutions', ['tenant_id', 'user_id', 'channel', 'expires_at'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_code_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_identities_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('channel', 'address', name='uq_user_identities_channel_address')
    )
    op.create_index('ix_user_identities_tenant', 'user_identities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    _create_resolution_indexes()
    _create_audit_partitions()
    _enable_row_level_security()
    _grant_app_role()


def _create_resolution_indexes() -> None:
    """Indices da cascata de resolucao (ORBI.md secao 6.9 e 7).

    HNSW no vetor, GIN trigram no nome canonico e GIN no tsvector. Todos com
    tenant_id no filtro, porque nenhuma busca cruza tenant.
    """
    op.execute(
        "CREATE INDEX ix_catalog_embedding_hnsw ON catalog "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_catalog_canonical_trgm ON catalog "
        "USING gin (canonical_name gin_trgm_ops)"
    )
    op.execute("CREATE INDEX ix_catalog_search_text ON catalog USING gin (search_text)")
    op.execute(
        "CREATE INDEX ix_entity_aliases_alias_trgm ON entity_aliases "
        "USING gin (alias gin_trgm_ops)"
    )


def _create_audit_partitions() -> None:
    """audit_logs e particionada por mes: expurgo vira DROP PARTITION (secao 16).

    A funcao cria a particao do mes indicado de forma idempotente; o cron mensal
    chama `orbi maintenance partitions`.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION orbi_ensure_audit_partition(target date)
        RETURNS text
        LANGUAGE plpgsql
        AS $$
        DECLARE
            start_date date := date_trunc('month', target)::date;
            end_date   date := (date_trunc('month', target) + interval '1 month')::date;
            part_name  text := 'audit_logs_' || to_char(start_date, 'YYYYMM');
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = part_name) THEN
                EXECUTE format(
                    'CREATE TABLE %I PARTITION OF audit_logs FOR VALUES FROM (%L) TO (%L)',
                    part_name, start_date, end_date
                );
                EXECUTE format('GRANT SELECT, INSERT ON %I TO orbi_app', part_name);
                EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', part_name);
                EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', part_name);
            END IF;
            RETURN part_name;
        END;
        $$
        """
    )
    # Particao de sobra para o passado distante e para o futuro nao previsto:
    # linha de auditoria nunca pode falhar por falta de particao.
    op.execute("CREATE TABLE audit_logs_default PARTITION OF audit_logs DEFAULT")
    # Defesa em profundidade: a politica do pai vale no acesso pelo pai, mas a
    # particao tambem e alcancavel diretamente por quem tem grant.
    op.execute("ALTER TABLE audit_logs_default ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_logs_default FORCE ROW LEVEL SECURITY")
    op.execute("SELECT orbi_ensure_audit_partition(current_date)")
    op.execute("SELECT orbi_ensure_audit_partition((current_date + interval '1 month')::date)")


def _enable_row_level_security() -> None:
    """Isolamento total entre tenants (ORBI.md secao 11).

    A politica le `app.tenant_id`, definido por `SET LOCAL` na unica dependency
    que abre sessao. Sem o SET, a politica nao casa e a consulta devolve zero
    linhas — falha fechada, nunca aberta.
    """
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
            """
        )

    # A tabela de tenants se isola pelo proprio id.
    op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenants_tenant_isolation ON tenants
        USING (id = nullif(current_setting('app.tenant_id', true), '')::uuid)
        WITH CHECK (id = nullif(current_setting('app.tenant_id', true), '')::uuid)
        """
    )

    # audit_logs e append-only: UPDATE e DELETE revogados no banco (secao 11).
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM {APP_ROLE}")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION orbi_audit_logs_append_only()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs e append-only: % nao e permitido', TG_OP;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION orbi_audit_logs_append_only()
        """
    )


def _grant_app_role() -> None:
    """O papel da aplicacao existe no compose e no provisionamento do servidor.

    Aqui apenas garantimos os grants; a criacao do papel e responsabilidade da
    infraestrutura, para que a senha nunca passe por migration.
    """
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                EXECUTE 'GRANT USAGE ON SCHEMA public TO {APP_ROLE}';
                EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE}';
                EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}';
                EXECUTE 'REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM {APP_ROLE}';
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS orbi_audit_logs_append_only()")
    op.execute("DROP FUNCTION IF EXISTS orbi_ensure_audit_partition(date)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_identities_tenant', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('ix_pending_resolutions_lookup', table_name='pending_resolutions')
    op.drop_table('pending_resolutions')
    op.drop_table('conversation_contexts')
    op.drop_index('ix_users_tenant', table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_tools')
    op.drop_table('tenant_settings')
    op.drop_table('role_tools')
    op.drop_table('role_capabilities')
    op.drop_index('ix_knowledge_models_tenant', table_name='knowledge_models')
    op.drop_table('knowledge_models')
    op.drop_index('ix_erp_connections_tenant', table_name='erp_connections')
    op.drop_table('erp_connections')
    op.drop_index('ix_entity_aliases_tenant', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_table('daily_usage')
    op.drop_index('ix_corrections_tenant_status', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('ix_catalog_sync_runs_tenant', table_name='catalog_sync_runs')
    op.drop_table('catalog_sync_runs')
    op.drop_index('ix_catalog_abbreviations_tenant', table_name='catalog_abbreviations')
    op.drop_table('catalog_abbreviations')
    op.drop_index('ix_catalog_tenant_type_active', table_name='catalog')
    op.drop_index('ix_catalog_tenant_code', table_name='catalog')
    op.drop_table('catalog')
    op.drop_table('tools')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('rate_limit_counters')
    op.drop_table('eval_runs')
    op.drop_table('capabilities')
    op.drop_index('ix_audit_logs_trace', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
