"""tenant roles

Revision ID: ca2d4fb90f19
Revises: d3e4f5a6b7c8
Create Date: 2026-08-30 16:54:28.406863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2d4fb90f19'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_role_capabilities',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('capability_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['capability_code'], ['capabilities.code'], name=op.f('fk_tenant_role_capabilities_capability_code_capabilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_role_capabilities_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'role_code', 'capability_code', name=op.f('pk_tenant_role_capabilities'))
    )
    op.create_table('tenant_roles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_roles_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'code', name=op.f('pk_tenant_roles'))
    )
    # ### end Alembic commands ###
    _enable_row_level_security()
    _grant_app_role()


def _grant_app_role() -> None:
    """Tabela nova precisa de GRANT explicito.

    O `ALTER DEFAULT PRIVILEGES` da infraestrutura some junto com o schema, entao
    depender dele faz a tabela nascer inacessivel em ambiente recriado. Toda
    migration que cria tabela repete este bloco.
    """
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'orbi_app') THEN
                EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_roles TO orbi_app';
                EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_role_capabilities '
                        'TO orbi_app';
            END IF;
        END
        $$
        """
    )


def _enable_row_level_security() -> None:
    """Papel proprio de um cliente e dado do cliente: RLS como qualquer outro."""
    for table in ("tenant_roles", "tenant_role_capabilities"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
            WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_roles')
    op.drop_table('tenant_role_capabilities')
    # ### end Alembic commands ###
